#!/bin/bash
# https://s3-us-west-2.amazonaws.com/imss-hpc/index.html to generate script
#SBATCH --time=48:00:00   # walltime
#SBATCH --gres=gpu:1
#SBATCH --gid=andersonlab

# Execute jobs in parallel
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd5_nl1_v7 --hidden_dim 5 --num_rnn_layers 1 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd10_nl1_v7 --hidden_dim 10 --num_rnn_layers 1 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd20_nl1_v7 --hidden_dim 20 --num_rnn_layers 1 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd50_nl1_v7 --hidden_dim 50 --num_rnn_layers 1 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd100_nl1_v7 --hidden_dim 100 --num_rnn_layers 1 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd5_nl2_v7 --hidden_dim 5 --num_rnn_layers 2 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd10_nl2_v7 --hidden_dim 10 --num_rnn_layers 2 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd20_nl2_v7 --hidden_dim 20 --num_rnn_layers 2 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd50_nl2_v7 --hidden_dim 50 --num_rnn_layers 2 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd100_nl2_v7 --hidden_dim 100 --num_rnn_layers 2 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd5_nl3_v7 --hidden_dim 5 --num_rnn_layers 3 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd10_nl3_v7 --hidden_dim 10 --num_rnn_layers 3 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd20_nl3_v7 --hidden_dim 20 --num_rnn_layers 3 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd50_nl3_v7 --hidden_dim 50 --num_rnn_layers 3 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/  &
srun --exclusive -N 1 -n 1 python test_run.py --output_path ./test_output_rnn_GRU_backwards_hd100_nl3_v7 --hidden_dim 100 --num_rnn_layers 3 --feature_style keypoints_only --use_glm_scores False --model_name GRUTagger --bidirectional True --lr 0.1 --use_gpu True --num_epochs 200 --train_path /groups/Andersonlab/CMS273/TRAIN_lite/ --test_path /groups/Andersonlab/CMS273/TEST_lite/
wait